[workspace]
resolver = "2"
members = [
    "crates/embedded-gui",
    "crates/embedded-gui-codegen",
    "crates/embedded-gui-macros",
]
exclude = [
    "size_harness",
]

[workspace.package]
version = "0.2.3"
edition = "2024"
rust-version = "1.87"
authors = ["Gerzain Mata <leftger@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/leftger/embedded-gui"
homepage = "https://github.com/leftger/embedded-gui"
documentation = "https://docs.rs/embedded-gui"
readme = "README.md"

[workspace.dependencies]
embedded-gui = { path = "crates/embedded-gui", version = "0.2.3" }
embedded-gui-codegen = { path = "crates/embedded-gui-codegen", version = "0.2.3" }
embedded-gui-macros = { path = "crates/embedded-gui-macros", version = "0.2.3" }

embedded-graphics-core = "0.4.1"
embedded-draw-target = "0.1.1"
embedded-graphics-framebuf = "0.3"
critical-section = "1.1"
heapless = "0.9"
embassy-time = { version = "0.5", default-features = false }
embassy-sync = { version = "0.8", default-features = false }
libm = { version = "0.2" }
micromath = { version = "2.1" }
embedded-graphics = { version = "0.8" }
embedded-text = { version = "0.7.3" }
embedded-layout = { version = "0.4.2" }
embedded-dsp = { version = "0.2.0", default-features = false }
embedded-3dgfx = { version = "0.5.5" }
nalgebra = { version = "0.35", default-features = false }

embedded-graphics-simulator = "0.8"
criterion = { version = "0.5", features = ["html_reports"] }
kdl = "4.7"
thiserror = "2.0"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
