//! File export and standalone Cargo crate project generator.

use embedded_gui_codegen::ScreenDef;
use std::fs;
use std::path::PathBuf;

/// Prompts user with a file open dialog for `.kdl` files and returns loaded content.
pub fn open_kdl_file_dialog() -> Option<(PathBuf, String)> {
    let file = rfd::FileDialog::new()
        .add_filter("KDL Screen Definition", &["kdl"])
        .pick_file()?;

    let content = fs::read_to_string(&file).ok()?;
    Some((file, content))
}

/// Prompts user with a file save dialog for `.kdl` files and saves content.
pub fn save_kdl_file_dialog(kdl_content: &str, default_name: &str) -> Option<PathBuf> {
    let file = rfd::FileDialog::new()
        .add_filter("KDL Screen Definition", &["kdl"])
        .set_file_name(format!("{}.kdl", default_name))
        .save_file()?;

    fs::write(&file, kdl_content).ok()?;
    Some(file)
}

/// Prompts user to choose a target folder and exports a complete standalone Cargo project.
pub fn export_standalone_crate_dialog(
    screen: &ScreenDef,
    kdl_content: &str,
    generated_rust: &str,
) -> Result<PathBuf, String> {
    let folder = rfd::FileDialog::new()
        .set_title("Choose Directory to Export Standalone Rust Crate")
        .pick_folder()
        .ok_or_else(|| "Export cancelled by user".to_string())?;

    let crate_name = screen.id.to_lowercase().replace(' ', "_");
    let project_dir = folder.join(&crate_name);
    fs::create_dir_all(&project_dir).map_err(|e| e.to_string())?;

    let src_dir = project_dir.join("src");
    fs::create_dir_all(&src_dir).map_err(|e| e.to_string())?;

    // 1. Cargo.toml
    let gui_version = env!("CARGO_PKG_VERSION");
    let cargo_toml = format!(
        r#"[package]
name = "{crate_name}"
version = "0.1.0"
edition = "2024"

[dependencies]
embedded-gui = "{gui_version}"
embedded-graphics = "0.8"
embedded-graphics-simulator = "0.6"
"#
    );
    fs::write(project_dir.join("Cargo.toml"), cargo_toml).map_err(|e| e.to_string())?;

    // 2. screen.kdl
    fs::write(project_dir.join("screen.kdl"), kdl_content).map_err(|e| e.to_string())?;

    // 3. src/main.rs with embedded-graphics-simulator runnable loop
    let main_rs = format!(
        r#"//! Autogenerated by Embedded GUI Studio
//! Run with: cargo run

use embedded_graphics::pixelcolor::Rgb565;
use embedded_graphics_simulator::{{OutputSettingsBuilder, SimulatorDisplay, SimulatorEvent, Window}};
use embedded_gui::prelude::*;

{generated_rust}

fn main() -> Result<(), core::convert::Infallible> {{
    let mut display: SimulatorDisplay<Rgb565> = SimulatorDisplay::new(
        embedded_graphics::geometry::Size::new({w}, {h}),
    );
    let output_settings = OutputSettingsBuilder::new().scale(2).build();
    let mut window = Window::new("{screen_id} Simulator", &output_settings);

    let screen = {screen_id}Screen::new();

    println!("⚡ Starting {screen_id} on simulated display ({w}x{h})...");

    'running: loop {{
        // Render UI screen
        display.clear(Rgb565::BLACK).ok();
        screen.render(&mut display).ok();
        window.update(&display);

        for event in window.events() {{
            match event {{
                SimulatorEvent::Quit => break 'running,
                _ => {{}}
            }}
        }}

        std::thread::sleep(std::time::Duration::from_millis(16));
    }}

    Ok(())
}}
"#,
        screen_id = screen.id,
        w = screen.width,
        h = screen.height,
        generated_rust = generated_rust,
    );
    fs::write(src_dir.join("main.rs"), main_rs).map_err(|e| e.to_string())?;

    // 4. README.md
    let readme = format!(
        r#"# {screen_id} Embedded GUI Project

Autogenerated standalone GUI project created with **Embedded GUI Studio**.

## Quick Start
```bash
cargo run
```

## Structure
- `screen.kdl`: Declarative KDL layout schema.
- `src/main.rs`: Generated Rust bindings with active desktop simulator runner.
"#,
        screen_id = screen.id,
    );
    fs::write(project_dir.join("README.md"), readme).map_err(|e| e.to_string())?;

    Ok(project_dir)
}
