[package]
name = "embedded-gui-macros"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Procedural macros for compiling KDL UI layouts into no_std Rust code for embedded-gui"

[lib]
proc-macro = true

[dependencies]
embedded-gui-codegen.workspace = true
image = { version = "0.25.9", default-features = false, features = ["png", "jpeg", "bmp"] }
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
