use crate::assets;
use crate::ast::*;
use crate::parser::*;
use core::fmt::Write as _;

/// Generates zero-allocation `#![no_std]` Rust code from a parsed `ScreenDef`.
pub fn generate_rust_code(screen: &ScreenDef) -> String {
    let mut out = String::new();

    let screen_name = &screen.id;
    let widget_struct_name = format!("{}Widgets", screen_name);
    let app_struct_name = format!("{}App", screen_name);
    let num_cols = screen.grid.cols.len();
    let num_rows = screen.grid.rows.len();
    let total_nodes = screen.grid.children.len();

    // File header
    let _ = writeln!(
        &mut out,
        "// Auto-generated by embedded-gui-codegen. DO NOT EDIT."
    );
    let _ = writeln!(&mut out, "use embedded_gui::prelude::*;");
    let _ = writeln!(&mut out);

    // Struct containing all named widget IDs
    let _ = writeln!(
        &mut out,
        "/// Strongly-typed widget IDs for {}.",
        screen_name
    );
    let _ = writeln!(&mut out, "#[derive(Clone, Copy, Debug)]");
    let _ = writeln!(&mut out, "pub struct {} {{", widget_struct_name);
    for (_, w) in &screen.grid.children {
        if let Some(id) = w.id() {
            let field_name = to_snake_case(id);
            let _ = writeln!(&mut out, "    pub {}: WidgetId,", field_name);
        }
    }
    let _ = writeln!(&mut out, "}}");
    let _ = writeln!(&mut out);

    // App struct
    let _ = writeln!(&mut out, "pub struct {} {{", app_struct_name);
    let _ = writeln!(&mut out, "    pub widgets: {},", widget_struct_name);
    let _ = writeln!(&mut out, "}}");
    let _ = writeln!(&mut out);

    // Impl block with build method
    let _ = writeln!(&mut out, "impl {} {{", app_struct_name);
    let _ = writeln!(&mut out, "    pub const WIDTH: u32 = {};", screen.width);
    let _ = writeln!(&mut out, "    pub const HEIGHT: u32 = {};", screen.height);
    if let Some(transition) = &screen.transition {
        let _ = writeln!(
            &mut out,
            "    pub const TRANSITION: ScreenTransitionSpec = ScreenTransitionSpec {{ effect: {}, duration_ms: {}, origin: {}, easing: {} }};",
            transition_effect_expr(&transition.preset),
            transition.duration_ms,
            transition_origin_expr(&transition.origin),
            easing_expr(&transition.easing),
        );
    }
    let _ = writeln!(
        &mut out,
        "    pub const NODE_COUNT: usize = {};",
        total_nodes
    );
    let _ = writeln!(&mut out);
    let _ = writeln!(
        &mut out,
        "    pub fn build<'a, const N: usize, const E: usize, const D: usize>("
    );
    let _ = writeln!(&mut out, "        gui: &mut GuiContext<'a, N, E, D>,");
    let _ = writeln!(&mut out, "    ) -> Result<Self, GuiError> {{");

    // Track arrays
    let _ = writeln!(&mut out, "        let col_tracks = [");
    for t in &screen.grid.cols {
        match t {
            GridTrackDef::Px(px) => {
                let _ = writeln!(&mut out, "            GridTrack::Px({}),", px);
            }
            GridTrackDef::Fr(fr) => {
                let _ = writeln!(&mut out, "            GridTrack::Fr({}),", fr);
            }
            GridTrackDef::Auto => {
                let _ = writeln!(&mut out, "            GridTrack::Auto,");
            }
        }
    }
    let _ = writeln!(&mut out, "        ];");

    let _ = writeln!(&mut out, "        let row_tracks = [");
    for t in &screen.grid.rows {
        match t {
            GridTrackDef::Px(px) => {
                let _ = writeln!(&mut out, "            GridTrack::Px({}),", px);
            }
            GridTrackDef::Fr(fr) => {
                let _ = writeln!(&mut out, "            GridTrack::Fr({}),", fr);
            }
            GridTrackDef::Auto => {
                let _ = writeln!(&mut out, "            GridTrack::Auto,");
            }
        }
    }
    let _ = writeln!(&mut out, "        ];");

    let _ = writeln!(
        &mut out,
        "        let grid = GridLayout::<{}, {}>::new(col_tracks, row_tracks)",
        num_cols, num_rows
    );
    let _ = writeln!(&mut out, "            .with_gap({})", screen.grid.gap);
    let _ = writeln!(
        &mut out,
        "            .with_padding(EdgeInsets::all({}));",
        screen.grid.padding
    );
    let _ = writeln!(&mut out);

    // Placements
    let _ = writeln!(&mut out, "        let placements = [");
    for (p, _) in &screen.grid.children {
        if p.col_span > 1 || p.row_span > 1 {
            let _ = writeln!(
                &mut out,
                "            GridPlacement::span({}, {}, {}, {}),",
                p.col, p.row, p.col_span, p.row_span
            );
        } else {
            let _ = writeln!(
                &mut out,
                "            GridPlacement::cell({}, {}),",
                p.col, p.row
            );
        }
    }
    let _ = writeln!(&mut out, "        ];");
    let _ = writeln!(
        &mut out,
        "        let mut cells = [Rect::empty(); {}];",
        total_nodes
    );
    let _ = writeln!(
        &mut out,
        "        grid.arrange_cells(gui.viewport(), &placements, &mut cells);"
    );
    let _ = writeln!(&mut out);

    // Widget builder instantiations
    let mut named_vars = Vec::new();
    for (idx, (_, w)) in screen.grid.children.iter().enumerate() {
        let var_name = if let Some(id) = w.id() {
            let name = to_snake_case(id);
            named_vars.push(name.clone());
            name
        } else {
            format!("_w{}", idx)
        };

        match w {
            WidgetDef::Label { text, style, .. } => {
                let st = style_expr(style.as_deref(), "Style::default()");
                let _ = writeln!(
                    &mut out,
                    "        let {} = gui.add_label(cells[{}], \"{}\", {})?;",
                    var_name, idx, text, st
                );
            }
            WidgetDef::Button {
                text,
                style,
                bg,
                fg,
                text_color,
                pressed_bg,
                pressed_fg,
                pressed_text,
                disabled_bg,
                disabled_fg,
                disabled_text,
                focused_bg,
                focused_fg,
                focused_text,
                border_color,
                corner_radius,
                ..
            } => {
                let has_custom_props = bg.is_some()
                    || fg.is_some()
                    || text_color.is_some()
                    || pressed_bg.is_some()
                    || pressed_fg.is_some()
                    || pressed_text.is_some()
                    || disabled_bg.is_some()
                    || disabled_fg.is_some()
                    || disabled_text.is_some()
                    || focused_bg.is_some()
                    || focused_fg.is_some()
                    || focused_text.is_some()
                    || border_color.is_some()
                    || corner_radius.is_some();

                let mut st = match style {
                    Some(s)
                        if s.starts_with("WidgetStyle::")
                            || s.starts_with("Style::")
                            || s.starts_with('{') =>
                    {
                        s.clone()
                    }
                    Some(s) if !has_custom_props => style_expr(Some(s.as_str()), "Style::button()"),
                    _ => "WidgetStyle::button()".to_string(),
                };

                if has_custom_props {
                    if let Some(c) = bg {
                        st.push_str(&format!(".with_bg({})", color_to_rust_expr(c)));
                    }
                    if let Some(c) = fg {
                        st.push_str(&format!(".with_fg({})", color_to_rust_expr(c)));
                    }
                    if let Some(c) = text_color {
                        st.push_str(&format!(".with_text({})", color_to_rust_expr(c)));
                    }
                    if let Some(c) = pressed_bg {
                        st.push_str(&format!(".with_pressed_bg({})", color_to_rust_expr(c)));
                    }
                    if let Some(c) = pressed_fg {
                        st.push_str(&format!(".with_pressed_fg({})", color_to_rust_expr(c)));
                    }
                    if let Some(c) = pressed_text {
                        st.push_str(&format!(".with_pressed_text({})", color_to_rust_expr(c)));
                    }
                    if let Some(c) = disabled_bg {
                        st.push_str(&format!(".with_disabled_bg({})", color_to_rust_expr(c)));
                    }
                    if let Some(c) = disabled_fg {
                        st.push_str(&format!(".with_disabled_fg({})", color_to_rust_expr(c)));
                    }
                    if let Some(c) = disabled_text {
                        st.push_str(&format!(".with_disabled_text({})", color_to_rust_expr(c)));
                    }
                    if let Some(c) = focused_bg {
                        st.push_str(&format!(".with_focused_bg({})", color_to_rust_expr(c)));
                    }
                    if let Some(c) = focused_fg {
                        st.push_str(&format!(".with_focused_fg({})", color_to_rust_expr(c)));
                    }
                    if let Some(c) = focused_text {
                        st.push_str(&format!(".with_focused_text({})", color_to_rust_expr(c)));
                    }
                    if let Some(c) = border_color {
                        st.push_str(&format!(".with_border_color({})", color_to_rust_expr(c)));
                    }
                    if let Some(r) = corner_radius {
                        st.push_str(&format!(".with_corner_radius({})", r));
                    }
                }

                let _ = writeln!(
                    &mut out,
                    "        let {} = gui.add_button(cells[{}], \"{}\", {})?;",
                    var_name, idx, text, st
                );
            }
            WidgetDef::Toggle { label, checked, .. } => {
                let _ = writeln!(
                    &mut out,
                    "        let {} = gui.add_toggle(cells[{}], \"{}\", {}, Style::default())?;",
                    var_name, idx, label, checked
                );
            }
            WidgetDef::Checkbox { label, checked, .. } => {
                let _ = writeln!(
                    &mut out,
                    "        let {} = gui.add_checkbox(cells[{}], \"{}\", {}, Style::default())?;",
                    var_name, idx, label, checked
                );
            }
            WidgetDef::Slider {
                min, max, value, ..
            } => {
                let _ = writeln!(
                    &mut out,
                    "        let {} = gui.add_slider(cells[{}], {}, {}, {}, Style::default())?;",
                    var_name, idx, min, max, value
                );
            }
            WidgetDef::Dropdown {
                options, selected, ..
            } => {
                let opts_joined = options
                    .iter()
                    .map(|s| format!("\"{}\"", s))
                    .collect::<Vec<_>>()
                    .join(", ");
                let _ = writeln!(
                    &mut out,
                    "        let {} = gui.add_dropdown(cells[{}], &[{}], {}, Style::panel())?;",
                    var_name, idx, opts_joined, selected
                );
            }
            WidgetDef::Roller {
                options, selected, ..
            } => {
                let opts_joined = options
                    .iter()
                    .map(|s| format!("\"{}\"", s))
                    .collect::<Vec<_>>()
                    .join(", ");
                let _ = writeln!(
                    &mut out,
                    "        let {} = gui.add_roller(cells[{}], &[{}], {}, Style::panel())?;",
                    var_name, idx, opts_joined, selected
                );
            }
            WidgetDef::Scale {
                mode,
                min,
                max,
                value,
                ..
            } => {
                let scale_mode = if mode.eq_ignore_ascii_case("radial") {
                    "ScaleMode::Radial"
                } else if mode.eq_ignore_ascii_case("linear_vertical") {
                    "ScaleMode::LinearVertical"
                } else {
                    "ScaleMode::LinearHorizontal"
                };
                let _ = writeln!(
                    &mut out,
                    "        let {} = gui.add_scale(cells[{}], {}, {:.1}, {:.1}, {:.1}, Style::panel())?;",
                    var_name, idx, scale_mode, min, max, value
                );
            }
            WidgetDef::Spinbox {
                min, max, value, ..
            } => {
                let _ = writeln!(
                    &mut out,
                    "        let {} = gui.add_spinbox(cells[{}], {}, {}, {}, Style::panel())?;",
                    var_name, idx, min, max, value
                );
            }
            WidgetDef::ProgressBar { value, .. } => {
                let _ = writeln!(
                    &mut out,
                    "        let {} = gui.add_progress_bar(cells[{}], {:.2}, Style::default())?;",
                    var_name, idx, value
                );
            }
            WidgetDef::SweepingArc {
                start_angle,
                end_angle,
                ..
            } => {
                let _ = writeln!(
                    &mut out,
                    "        let {} = gui.add_sweeping_arc(cells[{}], {}, {}, Style::panel())?;",
                    var_name, idx, start_angle, end_angle
                );
            }
            WidgetDef::BusyWheel { active, .. } => {
                let _ = writeln!(
                    &mut out,
                    "        let {} = gui.add_busy_wheel(cells[{}], {}, Style::panel())?;",
                    var_name, idx, active
                );
            }
            WidgetDef::Plotter { mode, .. } => {
                let chart_mode = if mode.eq_ignore_ascii_case("bar") {
                    "ChartMode::Bar"
                } else {
                    "ChartMode::Line"
                };
                let _ = writeln!(
                    &mut out,
                    "        let {} = gui.add_plotter(cells[{}], {}, Style::panel())?;",
                    var_name, idx, chart_mode
                );
            }
            WidgetDef::StatusBar { time, .. } => {
                let _ = writeln!(
                    &mut out,
                    "        let {} = gui.add_status_bar(cells[{}], \"{}\", Style::panel())?;",
                    var_name, idx, time
                );
            }
            WidgetDef::TimePicker {
                hour,
                minute,
                is_12h,
                is_pm,
                ..
            } => {
                let _ = writeln!(
                    &mut out,
                    "        let {} = gui.add_time_picker(cells[{}], {}, {}, {}, {}, Style::panel())?;",
                    var_name, idx, hour, minute, is_12h, is_pm
                );
            }
            WidgetDef::NumberPicker {
                min,
                max,
                value,
                unit,
                ..
            } => {
                let _ = writeln!(
                    &mut out,
                    "        let {} = gui.add_number_picker(cells[{}], {}, {}, {}, \"{}\", Style::panel())?;",
                    var_name, idx, min, max, value, unit
                );
            }
            WidgetDef::Dialog { title, message, .. } => {
                let _ = writeln!(
                    &mut out,
                    "        let {} = gui.add_dialog(cells[{}], \"{}\", \"{}\", Style::panel())?;",
                    var_name, idx, title, message
                );
            }
            WidgetDef::ContentIndicator { count, active, .. } => {
                let _ = writeln!(
                    &mut out,
                    "        let {} = gui.add_content_indicator(cells[{}], {}, {}, Style::panel())?;",
                    var_name, idx, count, active
                );
            }
            WidgetDef::CrumbsIndicator { count, active, .. } => {
                let _ = writeln!(
                    &mut out,
                    "        let {} = gui.add_crumbs_indicator(cells[{}], {}, {}, Style::panel())?;",
                    var_name, idx, count, active
                );
            }
            WidgetDef::Panel { style, .. } => {
                let st = style_expr(style.as_deref(), "Style::panel()");
                let _ = writeln!(
                    &mut out,
                    "        let {} = gui.add_panel(cells[{}], {})?;",
                    var_name, idx, st
                );
            }
            WidgetDef::Image {
                source, fit, mode, ..
            } => {
                let _ = writeln!(
                    &mut out,
                    "        let {} = gui.add_spacer(cells[{}])?; // image src={:?} fit={:?} mode={:?}; asset data is supplied by include_gui!",
                    var_name, idx, source, fit, mode
                );
            }
            WidgetDef::Spacer => {
                let _ = writeln!(
                    &mut out,
                    "        let {} = gui.add_spacer(cells[{}])?;",
                    var_name, idx
                );
            }
            WidgetDef::VectorPath {
                stroke_width,
                verbs,
                ..
            } => {
                let _ = writeln!(
                    &mut out,
                    "        let mut _path_{} = VectorPath::<{}>::new();",
                    var_name,
                    verbs.len().max(1)
                );
                for v in verbs {
                    match v {
                        PathVerbDef::MoveTo(x, y) => {
                            let _ = writeln!(
                                &mut out,
                                "        _path_{}.push(PathVerb::MoveTo(Point::new({}, {})));",
                                var_name, x, y
                            );
                        }
                        PathVerbDef::LineTo(x, y) => {
                            let _ = writeln!(
                                &mut out,
                                "        _path_{}.push(PathVerb::LineTo(Point::new({}, {})));",
                                var_name, x, y
                            );
                        }
                        PathVerbDef::QuadTo(cx, cy, x, y) => {
                            let _ = writeln!(
                                &mut out,
                                "        _path_{}.push(PathVerb::QuadTo(Point::new({}, {}), Point::new({}, {})));",
                                var_name, cx, cy, x, y
                            );
                        }
                        PathVerbDef::CubicTo(c1x, c1y, c2x, c2y, x, y) => {
                            let _ = writeln!(
                                &mut out,
                                "        _path_{}.push(PathVerb::CubicTo(Point::new({}, {}), Point::new({}, {}), Point::new({}, {})));",
                                var_name, c1x, c1y, c2x, c2y, x, y
                            );
                        }
                        PathVerbDef::Close => {
                            let _ = writeln!(
                                &mut out,
                                "        _path_{}.push(PathVerb::Close);",
                                var_name
                            );
                        }
                    }
                }
                let _ = writeln!(
                    &mut out,
                    "        let {} = gui.add_panel(cells[{}], Style::panel())?;",
                    var_name, idx
                );
                let _ = writeln!(
                    &mut out,
                    "        let _ = {}; // stroke_width: {}",
                    var_name, stroke_width
                );
            }
            WidgetDef::RectShape {
                radius,
                stroke_width,
                ..
            } => {
                let _ = writeln!(
                    &mut out,
                    "        let {} = gui.add_panel(cells[{}], Style::panel())?; // rect r={} sw={}",
                    var_name, idx, radius, stroke_width
                );
            }
            WidgetDef::LineShape { stroke_width, .. } => {
                let _ = writeln!(
                    &mut out,
                    "        let {} = gui.add_spacer(cells[{}])?; // line sw={}",
                    var_name, idx, stroke_width
                );
            }
            WidgetDef::CircleShape {
                radius,
                stroke_width,
                ..
            } => {
                let _ = writeln!(
                    &mut out,
                    "        let {} = gui.add_panel(cells[{}], Style::panel())?; // circle r={} sw={}",
                    var_name, idx, radius, stroke_width
                );
            }
            WidgetDef::Table { .. } => {
                let _ = writeln!(
                    &mut out,
                    "        let {} = gui.add_table(cells[{}], &[], Style::panel())?;",
                    var_name, idx
                );
            }
            WidgetDef::Carousel {
                items,
                selected,
                style,
                ..
            } => {
                let joined = items
                    .iter()
                    .map(|s| format!("\"{}\"", s))
                    .collect::<Vec<_>>()
                    .join(", ");
                let st = style_expr(style.as_deref(), "Style::label()");
                let _ = writeln!(
                    &mut out,
                    "        let {} = gui.add_carousel(cells[{}], &[{}], {}, {}, {})?;",
                    var_name,
                    idx,
                    joined,
                    selected,
                    carousel_spec_expr(w),
                    st
                );
            }
            WidgetDef::CompositeIcon { parts, .. } => {
                let sources = parts
                    .iter()
                    .map(|part| part.source.as_str())
                    .collect::<Vec<_>>()
                    .join(", ");
                let _ = writeln!(
                    &mut out,
                    "        let {} = gui.add_spacer(cells[{}])?; // icon parts=[{}]; asset data is supplied by include_gui!",
                    var_name, idx, sources
                );
            }
            WidgetDef::Mesh3d { source, .. } => {
                let _ = writeln!(
                    &mut out,
                    "        let {} = gui.add_spacer(cells[{}])?; // mesh src={:?}; geometry is supplied by include_gui!",
                    var_name, idx, source
                );
            }
        }
    }

    let _ = writeln!(&mut out);
    let _ = writeln!(&mut out, "        Ok(Self {{");
    let _ = writeln!(&mut out, "            widgets: {} {{", widget_struct_name);
    for name in &named_vars {
        let _ = writeln!(&mut out, "                {},", name);
    }
    let _ = writeln!(&mut out, "            }},");
    let _ = writeln!(&mut out, "        }})");
    let _ = writeln!(&mut out, "    }}");
    let _ = writeln!(&mut out);
    write_animation_method(
        &mut out,
        screen,
        "screen_enter",
        "start_screen_enter_animations",
    );
    write_animation_method(
        &mut out,
        screen,
        "screen_exit",
        "start_screen_exit_animations",
    );
    write_animation_method(&mut out, screen, "click", "start_click_animations");
    write_animation_method(&mut out, screen, "loop", "start_loop_animations");

    let _ = writeln!(
        &mut out,
        "    pub fn apply_theme<'a, const N: usize, const E: usize, const D: usize>("
    );
    let _ = writeln!(&mut out, "        &self,");
    let _ = writeln!(&mut out, "        _gui: &mut GuiContext<'a, N, E, D>,");
    let _ = writeln!(&mut out, "        _theme: Theme,");
    let _ = writeln!(&mut out, "    ) {{");
    let _ = writeln!(&mut out, "    }}");
    let _ = writeln!(&mut out);
    let _ = writeln!(
        &mut out,
        "    pub fn set_language<'a, const N: usize, const E: usize, const D: usize>("
    );
    let _ = writeln!(&mut out, "        &self,");
    let _ = writeln!(&mut out, "        _gui: &mut GuiContext<'a, N, E, D>,");
    let _ = writeln!(&mut out, "        _table: &TranslationTable,");
    let _ = writeln!(&mut out, "    ) {{");
    let _ = writeln!(&mut out, "    }}");
    let _ = writeln!(&mut out, "}}");

    out
}

fn easing_expr(easing: &str) -> &'static str {
    match easing {
        "in_sine" => "Easing::InSine",
        "out_sine" => "Easing::OutSine",
        "in_out_sine" => "Easing::InOutSine",
        "out_cubic" => "Easing::OutCubic",
        "out_back" => "Easing::OutBack",
        "out_bounce" => "Easing::OutBounce",
        "moook" => "Easing::Moook",
        _ => "Easing::Linear",
    }
}

fn transition_effect_expr(preset: &str) -> &'static str {
    match preset {
        "window_push" => "ScreenTransitionEffect::PushMoook",
        "window_pop" => "ScreenTransitionEffect::PopMoook",
        "fade" => "ScreenTransitionEffect::Fade",
        "timeline_slide" => "ScreenTransitionEffect::SlideLeft",
        "modal_present" => "ScreenTransitionEffect::ModalSlideUp",
        "modal_dismiss" => "ScreenTransitionEffect::ModalSlideDown",
        "shutter_left" => "ScreenTransitionEffect::ShutterLeft",
        "shutter_right" => "ScreenTransitionEffect::ShutterRight",
        "shutter_up" => "ScreenTransitionEffect::ShutterUp",
        "shutter_down" => "ScreenTransitionEffect::ShutterDown",
        "port_hole_left" => "ScreenTransitionEffect::PortHoleLeft",
        "port_hole_right" => "ScreenTransitionEffect::PortHoleRight",
        "port_hole_up" => "ScreenTransitionEffect::PortHoleUp",
        "port_hole_down" => "ScreenTransitionEffect::PortHoleDown",
        "round_flip_to_launcher" => "ScreenTransitionEffect::RoundFlipRight",
        "round_flip_from_launcher" => "ScreenTransitionEffect::RoundFlipLeft",
        _ => "ScreenTransitionEffect::None",
    }
}

fn transition_origin_expr(origin: &str) -> &'static str {
    match origin {
        "top_left" => "ScreenTransitionOrigin::TopLeft",
        "top" => "ScreenTransitionOrigin::Top",
        "top_right" => "ScreenTransitionOrigin::TopRight",
        "left" => "ScreenTransitionOrigin::Left",
        "right" => "ScreenTransitionOrigin::Right",
        "bottom_left" => "ScreenTransitionOrigin::BottomLeft",
        "bottom" => "ScreenTransitionOrigin::Bottom",
        "bottom_right" => "ScreenTransitionOrigin::BottomRight",
        _ => "ScreenTransitionOrigin::Center",
    }
}

fn animation_expr(from: &str, to: &str, animation: &WidgetAnimationDef, ping_pong: bool) -> String {
    let mut expr = format!(
        "Animation::new(({from}) as f32, ({to}) as f32, {}, {}).with_delay({})",
        animation.duration_ms,
        easing_expr(&animation.easing),
        animation.delay_ms
    );
    if ping_pong || animation.repeat != 1 {
        let mode = if ping_pong {
            "RepeatMode::PingPong"
        } else {
            "RepeatMode::Loop"
        };
        let count = if animation.repeat == 0 {
            "None".to_string()
        } else {
            format!("Some({})", animation.repeat.saturating_sub(1))
        };
        let _ = write!(
            &mut expr,
            ".with_repeat_mode({mode}).with_repeat_count({count})"
        );
    }
    expr
}

fn write_binding(
    out: &mut String,
    widget: &str,
    property: &str,
    from: &str,
    to: &str,
    animation: &WidgetAnimationDef,
    ping_pong: bool,
) {
    let expr = animation_expr(from, to, animation, ping_pong);
    let _ = writeln!(
        out,
        "            animator.bind_property_with_policy(self.widgets.{widget}, AnimatedProperty::{property}, {expr}, AnimationConflictPolicy::Replace)?;"
    );
}

fn write_animation_method(out: &mut String, screen: &ScreenDef, trigger: &str, method: &str) {
    let configured: Vec<_> = screen
        .grid
        .children
        .iter()
        .filter_map(|(placement, widget)| {
            let animation = placement.animation.as_ref()?;
            (animation.trigger == trigger)
                .then(|| widget.id().map(|id| (to_snake_case(id), animation)))
                .flatten()
        })
        .collect();
    if configured.is_empty() {
        return;
    }

    let _ = writeln!(
        out,
        "    pub fn {method}<'a, const N: usize, const E: usize, const D: usize, const TRACKS: usize, const BINDINGS: usize>("
    );
    let _ = writeln!(out, "        &self,");
    let _ = writeln!(out, "        gui: &GuiContext<'a, N, E, D>,");
    let _ = writeln!(
        out,
        "        animator: &mut WidgetAnimator<TRACKS, BINDINGS>,"
    );
    let _ = writeln!(out, "    ) -> Result<(), WidgetAnimationError> {{");

    for (widget, animation) in configured {
        let _ = writeln!(
            out,
            "        if let Some(node) = gui.widgets().iter().find(|node| node.id == self.widgets.{widget}) {{"
        );
        let _ = writeln!(out, "            let base = node.rect;");
        let reverse = trigger == "screen_exit";
        match animation.preset.as_str() {
            "fade_in" => {
                let (from, to) = if reverse { ("255", "0") } else { ("0", "255") };
                write_binding(out, &widget, "Opacity", from, to, animation, false);
            }
            "fade_in_up" => {
                let (from_y, to_y, from_alpha, to_alpha) = if reverse {
                    ("base.y", "base.y + 24", "255", "0")
                } else {
                    ("base.y + 24", "base.y", "0", "255")
                };
                write_binding(out, &widget, "WidgetY", from_y, to_y, animation, false);
                write_binding(
                    out, &widget, "Opacity", from_alpha, to_alpha, animation, false,
                );
            }
            "slide_in_left" => {
                let (from, to) = if reverse {
                    ("base.x", "base.x - base.w as i32")
                } else {
                    ("base.x - base.w as i32", "base.x")
                };
                write_binding(out, &widget, "WidgetX", from, to, animation, false);
            }
            "slide_in_right" => {
                let (from, to) = if reverse {
                    ("base.x", "base.x + base.w as i32")
                } else {
                    ("base.x + base.w as i32", "base.x")
                };
                write_binding(out, &widget, "WidgetX", from, to, animation, false);
            }
            "slide_in_up" => {
                let (from, to) = if reverse {
                    ("base.y", "base.y + base.h as i32")
                } else {
                    ("base.y + base.h as i32", "base.y")
                };
                write_binding(out, &widget, "WidgetY", from, to, animation, false);
            }
            "slide_in_down" => {
                let (from, to) = if reverse {
                    ("base.y", "base.y - base.h as i32")
                } else {
                    ("base.y - base.h as i32", "base.y")
                };
                write_binding(out, &widget, "WidgetY", from, to, animation, false);
            }
            "zoom_in" => {
                let (from_w, to_w, from_h, to_h) = if reverse {
                    ("base.w", "1", "base.h", "1")
                } else {
                    ("1", "base.w", "1", "base.h")
                };
                write_binding(out, &widget, "WidgetWidth", from_w, to_w, animation, false);
                write_binding(out, &widget, "WidgetHeight", from_h, to_h, animation, false);
            }
            "pulse" | "breathe" => {
                write_binding(out, &widget, "Opacity", "150", "255", animation, true);
            }
            "shake" => {
                write_binding(
                    out,
                    &widget,
                    "WidgetX",
                    "base.x - 5",
                    "base.x + 5",
                    animation,
                    true,
                );
            }
            _ => {}
        }
        let _ = writeln!(out, "        }}");
    }
    let _ = writeln!(out, "        Ok(())");
    let _ = writeln!(out, "    }}");
    let _ = writeln!(out);
}

/// Renders a [`WidgetDef::Carousel`]'s parameters as a `CarouselSpec` literal.
fn carousel_spec_expr(widget: &WidgetDef) -> String {
    let WidgetDef::Carousel {
        item_step,
        visible,
        shift,
        mask_top,
        mask_bottom,
        fade,
        indicator,
        pulse,
        ..
    } = widget
    else {
        return "CarouselSpec::default()".to_string();
    };
    format!(
        "CarouselSpec {{ item_step: {item_step}, visible_slots: {visible}, shift: {shift}, \
mask_top: {mask_top}, mask_bottom: {mask_bottom}, fade_edges: {fade}, indicator: {indicator}, \
indicator_pulse: {pulse}, ..CarouselSpec::default() }}"
    )
}

/// A 1bpp icon layer resolved by a project-aware caller.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct IconAssetDef {
    pub source: String,
    pub bitmap: assets::MonoBitmapData,
}

/// A screen font resolved to embeddable bitmap data.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct FontBinaryDef {
    pub name: String,
    pub font: assets::BitmapFontData,
}

/// Mesh geometry resolved by a project-aware caller.
#[derive(Clone, Debug, PartialEq)]
pub struct MeshAssetDef {
    pub source: String,
    pub mesh: assets::MeshData,
}

/// Everything `include_gui!` resolved off disk for one screen.
#[derive(Clone, Debug, Default, PartialEq)]
pub struct ProjectAssets {
    pub images: Vec<ImageAssetDef>,
    pub icons: Vec<IconAssetDef>,
    pub fonts: Vec<FontBinaryDef>,
    pub meshes: Vec<MeshAssetDef>,
}

/// Generates Rust code with project image nodes backed by static RGB565 arrays.
///
/// Plain [`generate_rust_code`] intentionally leaves image nodes as spacers
/// because a standalone KDL string has no filesystem base. `include_gui!`
/// resolves those files and calls this variant.
pub fn generate_rust_code_with_image_assets(
    screen: &ScreenDef,
    assets: &[ImageAssetDef],
) -> String {
    generate_rust_code_with_assets(
        screen,
        &ProjectAssets {
            images: assets.to_vec(),
            ..ProjectAssets::default()
        },
    )
}

/// Generates Rust code with every project asset resolved: images, 1bpp icon
/// parts, imported fonts, and mesh geometry.
pub fn generate_rust_code_with_assets(screen: &ScreenDef, assets: &ProjectAssets) -> String {
    let mut out = generate_rust_code(screen);
    let mut declarations = String::new();

    for font in &assets.fonts {
        let const_name = font_const_name(&font.name);
        let data = &font.font;
        let _ = writeln!(
            &mut declarations,
            "static {}_GLYPHS: [u8; {}] = [",
            const_name,
            data.glyphs.len()
        );
        for chunk in data.glyphs.chunks(16) {
            let values = chunk
                .iter()
                .map(|byte| format!("0x{byte:02X}"))
                .collect::<Vec<_>>()
                .join(", ");
            let _ = writeln!(&mut declarations, "    {},", values);
        }
        let _ = writeln!(&mut declarations, "];");
        let _ = writeln!(
            &mut declarations,
            "static {const}: BitmapFont = BitmapFont {{ width: {w}, height: {h}, advance: {adv}, \
        line_height: {lh}, first_char: {first}, bytes_per_row: {bpr}, glyphs: &{const}_GLYPHS }};\n",
            const = const_name,
            w = data.width,
            h = data.height,
            adv = data.advance,
            lh = data.line_height,
            first = data.first_char,
            bpr = data.bytes_per_row,
        );
    }

    // Fonts referenced by labels and carousels replace the default style font.
    for (idx, (_, widget)) in screen.grid.children.iter().enumerate() {
        let (font_name, var_name) = match widget {
            WidgetDef::Label { font: Some(f), .. } | WidgetDef::Carousel { font: Some(f), .. } => (
                f,
                widget
                    .id()
                    .map(to_snake_case)
                    .unwrap_or_else(|| format!("_w{}", idx)),
            ),
            _ => continue,
        };
        if !assets.fonts.iter().any(|f| f.name == *font_name) {
            continue;
        }
        let font_expr = format!(
            "{{ let mut style = Style::label(); style.font = FontId::Bitmap(&{}); style }}",
            font_const_name(font_name)
        );
        let prefix = format!("        let {} = gui.add_", var_name);
        out = out
            .lines()
            .map(|line| {
                if !line.starts_with(&prefix) {
                    return line.to_string();
                }
                // The style is always the final argument of the builder call.
                match (line.rfind(", "), line.rfind(")?;")) {
                    (Some(start), Some(end)) if start < end => {
                        format!("{}, {}{}", &line[..start], font_expr, &line[end..])
                    }
                    _ => line.to_string(),
                }
            })
            .collect::<Vec<_>>()
            .join("\n");
        out.push('\n');
    }

    for (idx, (_, widget)) in screen.grid.children.iter().enumerate() {
        let var_name = widget
            .id()
            .map(to_snake_case)
            .unwrap_or_else(|| format!("widget_{}", idx));
        match widget {
            WidgetDef::CompositeIcon {
                id,
                parts,
                scale,
                align,
                tint,
                ..
            } => {
                let mut part_exprs = Vec::new();
                for (part_idx, part) in parts.iter().enumerate() {
                    let Some(asset) = assets.icons.iter().find(|a| a.source == part.source) else {
                        continue;
                    };
                    let bits_name = format!("__ICON_{}_{}_BITS", idx, part_idx);
                    let _ = writeln!(
                        &mut declarations,
                        "static {}: [u8; {}] = [",
                        bits_name,
                        asset.bitmap.bits.len()
                    );
                    for chunk in asset.bitmap.bits.chunks(16) {
                        let values = chunk
                            .iter()
                            .map(|byte| format!("0x{byte:02X}"))
                            .collect::<Vec<_>>()
                            .join(", ");
                        let _ = writeln!(&mut declarations, "    {},", values);
                    }
                    let _ = writeln!(&mut declarations, "];\n");
                    let tint_expr = match part.tint.as_deref().or(tint.as_deref()) {
                        Some(color) => format!("Some({})", rgb565_expr(color)),
                        None => "None".to_string(),
                    };
                    part_exprs.push(format!(
                        "    IconPart {{ bitmap: MonoBitmap {{ width: {w}, height: {h}, bits: &{bits} }}, \
dx: {dx}, dy: {dy}, visible: {vis}, tint: {tint} }},",
                        w = asset.bitmap.width,
                        h = asset.bitmap.height,
                        bits = bits_name,
                        dx = part.dx,
                        dy = part.dy,
                        vis = part.visible,
                        tint = tint_expr,
                    ));
                }
                if part_exprs.is_empty() {
                    continue;
                }
                let parts_name = format!("__ICON_{}_PARTS", idx);
                // `pub` so firmware can copy into a mutable buffer and flip
                // `visible`/`tint` without rebuilding the screen. Prefer the
                // widget id when present so call sites read as `WEAPON_PARTS`.
                let pub_alias = id.as_ref().map(|name| {
                    let upper = name
                        .chars()
                        .map(|c| {
                            if c.is_ascii_alphanumeric() {
                                c.to_ascii_uppercase()
                            } else {
                                '_'
                            }
                        })
                        .collect::<String>();
                    format!("{upper}_PARTS")
                });
                let _ = writeln!(
                    &mut declarations,
                    "pub static {}: [IconPart<'static>; {}] = [\n{}\n];\n",
                    parts_name,
                    part_exprs.len(),
                    part_exprs.join("\n")
                );
                if let Some(alias) = pub_alias.as_ref() {
                    if alias != &parts_name {
                        let _ = writeln!(
                            &mut declarations,
                            "/// Seed for a firmware-owned mutable copy of the `{id}` icon parts.\n\
pub static {alias}: [IconPart<'static>; {n}] = {parts};\n",
                            id = id.as_deref().unwrap_or("icon"),
                            n = part_exprs.len(),
                            parts = parts_name,
                        );
                    }
                }

                let sources = parts
                    .iter()
                    .map(|part| part.source.as_str())
                    .collect::<Vec<_>>()
                    .join(", ");
                let needle = format!(
                    "        let {} = gui.add_spacer(cells[{}])?; // icon parts=[{}]; asset data is supplied by include_gui!",
                    var_name, idx, sources
                );
                let align_expr = if align == "top_left" {
                    "IconAlign::TopLeft"
                } else {
                    "IconAlign::Center"
                };
                let replacement = format!(
                    "        let {} = gui.add_composite_icon(cells[{}], &{}, CompositeIconSpec {{ scale: {}, align: {}, paper: None }}, Style::default())?;",
                    var_name, idx, parts_name, scale, align_expr
                );
                out = out.replace(&needle, &replacement);
            }
            WidgetDef::Mesh3d {
                source,
                shading,
                color,
                scale,
                roll,
                pitch,
                yaw,
                camera_distance,
                fov,
                ..
            } => {
                let Some(asset) = assets.meshes.iter().find(|a| a.source == *source) else {
                    continue;
                };
                let mesh = &asset.mesh;
                let base = format!("__MESH_{}", idx);
                let _ = writeln!(
                    &mut declarations,
                    "static {}_VERTICES: [[f32; 3]; {}] = [",
                    base,
                    mesh.vertices.len()
                );
                for v in &mesh.vertices {
                    let _ = writeln!(
                        &mut declarations,
                        "    [{:?}, {:?}, {:?}],",
                        v[0], v[1], v[2]
                    );
                }
                let _ = writeln!(&mut declarations, "];");
                let _ = writeln!(
                    &mut declarations,
                    "static {}_FACES: [[usize; 3]; {}] = [",
                    base,
                    mesh.faces.len()
                );
                for f in &mesh.faces {
                    let _ = writeln!(&mut declarations, "    [{}, {}, {}],", f[0], f[1], f[2]);
                }
                let _ = writeln!(&mut declarations, "];");
                let _ = writeln!(
                    &mut declarations,
                    "static {}_NORMALS: [[f32; 3]; {}] = [",
                    base,
                    mesh.normals.len()
                );
                for n in &mesh.normals {
                    let _ = writeln!(
                        &mut declarations,
                        "    [{:?}, {:?}, {:?}],",
                        n[0], n[1], n[2]
                    );
                }
                let _ = writeln!(&mut declarations, "];\n");

                let shading_expr = match shading.as_str() {
                    "points" => "MeshShading::Points",
                    "lines" | "wireframe" => "MeshShading::Lines",
                    "lit" => "MeshShading::Lit",
                    _ => "MeshShading::Solid",
                };
                let color_expr = match color.as_deref() {
                    Some(c) => rgb565_expr(c),
                    None => "Rgb565::new(31, 63, 31)".to_string(),
                };
                // The panel is a free function rather than a widget: the 3D
                // rasterizer needs a Z-buffer the caller owns.
                let _ = writeln!(
                    &mut declarations,
                    "/// Mesh panel for the `{source}` node. Render it with\n\
/// `embedded_gui::interop::three_d::render_mesh_panel` using the rect of the\n\
/// `{var_name}` widget; requires embedded-gui's `embedded-3dgfx` feature.\n\
pub fn {var_name}_mesh_panel() -> MeshPanel<'static> {{\n\
    let mut panel = MeshPanel::new(\n\
        Geometry {{\n\
            vertices: &{base}_VERTICES,\n\
            faces: &{base}_FACES,\n\
            normals: &{base}_NORMALS,\n\
            ..Geometry::default()\n\
        }},\n\
        {color_expr},\n\
    );\n\
    panel.shading = {shading_expr};\n\
    panel.scale = {scale:?};\n\
    panel.attitude = ({roll:?}, {pitch:?}, {yaw:?});\n\
    panel.camera_distance = {camera_distance:?};\n\
    panel.fov = {fov:?};\n\
    panel\n\
}}\n"
                );
            }
            _ => {}
        }
    }

    for (idx, (_, widget)) in screen.grid.children.iter().enumerate() {
        let WidgetDef::Image {
            source, fit, mode, ..
        } = widget
        else {
            continue;
        };
        let Some(asset) = assets.images.iter().find(|asset| asset.source == *source) else {
            continue;
        };
        let var_name = widget
            .id()
            .map(to_snake_case)
            .unwrap_or_else(|| format!("widget_{}", idx));
        let const_name = format!("__IMAGE_ASSET_{}_PIXELS", idx);
        let _ = writeln!(&mut declarations, "const {}: &[u16] = &[", const_name);
        for chunk in asset.pixels.chunks(12) {
            let values = chunk
                .iter()
                .map(|pixel| format!("0x{pixel:04X}"))
                .collect::<Vec<_>>()
                .join(", ");
            let _ = writeln!(&mut declarations, "    {},", values);
        }
        let _ = writeln!(&mut declarations, "];\n");

        let needle = format!(
            "        let {} = gui.add_spacer(cells[{}])?; // image src={:?} fit={:?} mode={:?}; asset data is supplied by include_gui!",
            var_name, idx, source, fit, mode
        );
        let fit_expr = if fit == "center" {
            "ImageFit::Center"
        } else {
            "ImageFit::Stretch"
        };
        let replacement = format!(
            "        let {} = gui.add_image(cells[{}], ImageRef::new({}, {}, {}), {}, Style::default())?;",
            var_name, idx, asset.width, asset.height, const_name, fit_expr
        );
        out = out.replace(&needle, &replacement);
    }

    if !assets.meshes.is_empty() {
        declarations.insert_str(
            0,
            "use embedded_gui::interop::three_d::{Geometry, MeshPanel, MeshShading};\n\n",
        );
    }

    if !declarations.is_empty() {
        let marker = "use embedded_gui::prelude::*;\n";
        out = out.replacen(marker, &format!("{marker}\n{declarations}"), 1);
    }
    out
}

/// Rust-cases a font name into the identifier of its generated static.
fn font_const_name(name: &str) -> String {
    let mut out = String::from("__FONT_");
    for ch in name.chars() {
        out.push(if ch.is_ascii_alphanumeric() {
            ch.to_ascii_uppercase()
        } else {
            '_'
        });
    }
    out
}

/// Renders a color token (`#RRGGBB`, `#RGB`, or a palette name) as an
/// `Rgb565::new(..)` literal.
fn rgb565_expr(token: &str) -> String {
    let (r, g, b) = match token.trim().trim_start_matches('#') {
        hex if hex.len() == 6 && token.trim_start().starts_with('#') => {
            let byte = |i: usize| u8::from_str_radix(&hex[i..i + 2], 16).unwrap_or(0);
            (byte(0), byte(2), byte(4))
        }
        hex if hex.len() == 3 && token.trim_start().starts_with('#') => {
            let nib = |i: usize| {
                let v = u8::from_str_radix(&hex[i..i + 1], 16).unwrap_or(0);
                v * 17
            };
            (nib(0), nib(1), nib(2))
        }
        "black" => (0, 0, 0),
        "red" | "danger" => (255, 0, 0),
        "green" | "success" => (0, 255, 0),
        "blue" => (0, 0, 255),
        "yellow" | "warning" => (255, 255, 0),
        "cyan" | "accent" => (0, 255, 255),
        "magenta" => (255, 0, 255),
        _ => (255, 255, 255),
    };
    format!(
        "Rgb565::new({}, {}, {})",
        r as u16 * 31 / 255,
        g as u16 * 63 / 255,
        b as u16 * 31 / 255
    )
}
