#!/usr/bin/env python3
"""
Generates an animated preview GIF for embedded-gui-studio.
Captures the dual-pane IDE with live KDL editing, animated oscilloscope/motion canvas preview,
and the generated zero-allocation Rust code tab.
"""

import math
import os
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_GIF = REPO_ROOT / "docs" / "screenshots" / "embedded_gui_studio_preview.gif"

W, H = 840, 520

# Colors (Nord / Modern Dark palette)
BG_WINDOW = (24, 26, 32)
BG_TITLEBAR = (18, 20, 24)
BG_TOPBAR = (28, 32, 40)
BG_EDITOR = (19, 21, 26)
BG_PANEL = (22, 25, 31)
BG_LCD = (10, 14, 20)
BORDER_COLOR = (45, 52, 65)
TEXT_WHITE = (235, 240, 250)
TEXT_DIM = (130, 140, 155)
TEXT_COMMENT = (95, 105, 120)
TEXT_KW = (235, 100, 140)
TEXT_PROP = (100, 180, 245)
TEXT_STR = (150, 225, 140)
TEXT_NUM = (240, 175, 95)
ACCENT_BLUE = (45, 115, 230)
ACCENT_GREEN = (60, 220, 130)
ACCENT_CYAN = (60, 230, 200)

KDL_LINES = [
    ('screen id="ScopeScreen" width=320 height=240 {', TEXT_KW),
    ('    grid cols="1fr 80px" rows="30px 1fr 40px" gap=4 {', TEXT_PROP),
    ('        status_bar id="clock" time="14:32" col=0 row=0 col_span=2', TEXT_WHITE),
    ('        plotter id="wave_view" mode="sine" col=0 row=1', ACCENT_CYAN),
    ('        roller id="v_div" selected=1 col=1 row=1 {', TEXT_WHITE),
    ('            option "100mV"', TEXT_STR),
    ('            option "500mV"', TEXT_STR),
    ('            option "1V"', TEXT_STR),
    ('            option "5V"', TEXT_STR),
    ('        }', TEXT_WHITE),
    ('        button id="btn_run" text="RUN/STOP" style="accent" col=0 row=2', TEXT_WHITE),
    ('        button id="btn_single" text="SINGLE" col=1 row=2', TEXT_WHITE),
    ('    }', TEXT_PROP),
    ('}', TEXT_KW),
]

RUST_LINES = [
    ('// Auto-generated by embedded-gui-codegen. DO NOT EDIT.', TEXT_COMMENT),
    ('use embedded_gui::prelude::*;', TEXT_KW),
    ('', TEXT_WHITE),
    ('pub struct ScopeScreenWidgets {', TEXT_KW),
    ('    pub clock: WidgetId,', TEXT_WHITE),
    ('    pub wave_view: WidgetId,', ACCENT_CYAN),
    ('    pub v_div: WidgetId,', TEXT_WHITE),
    ('    pub btn_run: WidgetId,', TEXT_WHITE),
    ('    pub btn_single: WidgetId,', TEXT_WHITE),
    ('}', TEXT_WHITE),
    ('', TEXT_WHITE),
    ('impl ScopeScreenApp {', TEXT_KW),
    ('    pub const WIDTH: u32 = 320;', TEXT_NUM),
    ('    pub const HEIGHT: u32 = 240;', TEXT_NUM),
    ('    pub fn build(gui: &mut GuiContext) -> Result<Self, GuiError> {', TEXT_KW),
    ('        let col_tracks = [GridTrack::Fr(1), GridTrack::Px(80)];', TEXT_WHITE),
    ('        let row_tracks = [GridTrack::Px(30), GridTrack::Fr(1), GridTrack::Px(40)];', TEXT_WHITE),
    ('        let grid = GridLayout::<2, 3>::new(col_tracks, row_tracks);', TEXT_WHITE),
    ('        // ... builds deterministic, zero-allocation UI nodes', TEXT_COMMENT),
    ('    }', TEXT_KW),
    ('}', TEXT_WHITE),
]

def create_frame(frame_idx: int, total_frames: int) -> Image.Image:
    img = Image.new("RGB", (W, H), BG_WINDOW)
    draw = ImageDraw.Draw(img)

    t = (frame_idx / total_frames) * 4.0  # 4 seconds animation cycle
    show_rust_tab = 45 <= frame_idx < 65  # show rust tab for a brief moment in the loop

    # 1. Window Frame / Titlebar
    draw.rectangle([(0, 0), (W, 30)], fill=BG_TITLEBAR)
    draw.line([(0, 30), (W, 30)], fill=BORDER_COLOR, width=1)

    # Traffic light window dots
    draw.ellipse([(12, 10), (22, 20)], fill=(240, 90, 80))
    draw.ellipse([(28, 10), (38, 20)], fill=(240, 190, 60))
    draw.ellipse([(44, 10), (54, 20)], fill=(70, 200, 90))

    draw.text((68, 8), "⚡ Embedded GUI Studio - KDL Live Preview & Codegen", fill=TEXT_WHITE)

    # 2. Top Toolbar
    draw.rectangle([(0, 31), (W, 64)], fill=BG_TOPBAR)
    draw.line([(0, 64), (W, 64)], fill=BORDER_COLOR, width=1)

    # Toolbar buttons
    draw.rounded_rectangle([(12, 36), (100, 58)], radius=4, fill=(40, 46, 58), outline=BORDER_COLOR)
    draw.text((20, 40), "📄 Presets ▼", fill=TEXT_WHITE)

    draw.rounded_rectangle([(108, 36), (225, 58)], radius=4, fill=(40, 46, 58), outline=BORDER_COLOR)
    draw.text((116, 40), "📋 Copy Rust Code", fill=TEXT_WHITE)

    # Motion Toolbar (Center)
    draw.rounded_rectangle([(240, 36), (308, 58)], radius=4, fill=ACCENT_BLUE if not show_rust_tab else (40, 46, 58))
    draw.text((248, 40), "⏸ Pause" if not show_rust_tab else "▶ Play", fill=TEXT_WHITE)

    draw.text((318, 41), "Time:", fill=TEXT_DIM)
    draw.rounded_rectangle([(355, 45), (450, 49)], radius=2, fill=(50, 56, 68))
    scrubber_x = 355 + int((t / 4.0) * 95)
    draw.ellipse([(scrubber_x - 4, 41), (scrubber_x + 4, 53)], fill=ACCENT_BLUE)
    draw.text((458, 41), f"{t:.2f}s", fill=TEXT_WHITE)

    # Status Badge (Right)
    draw.rounded_rectangle([(W - 140, 36), (W - 12, 58)], radius=4, fill=(20, 45, 30), outline=(40, 100, 60))
    draw.text((W - 130, 40), "✓ Valid (5 nodes)", fill=ACCENT_GREEN)

    # 3. Main Split View
    split_x = 380

    # Left: KDL Editor
    draw.rectangle([(0, 65), (split_x, H)], fill=BG_EDITOR)
    draw.line([(split_x, 65), (split_x, H)], fill=BORDER_COLOR, width=1)

    draw.rectangle([(0, 65), (split_x, 92)], fill=(25, 28, 36))
    draw.text((14, 71), "KDL Screen Definition", fill=TEXT_WHITE)
    draw.line([(0, 92), (split_x, 92)], fill=BORDER_COLOR, width=1)

    y_kdl = 102
    for line, color in KDL_LINES:
        draw.text((14, y_kdl), line, fill=color)
        y_kdl += 18

    # Right: Tab Bar
    draw.rectangle([(split_x + 1, 65), (W, 95)], fill=BG_PANEL)
    draw.line([(split_x + 1, 95), (W, 95)], fill=BORDER_COLOR, width=1)

    # Tabs
    tab1_bg = BG_PANEL if show_rust_tab else ACCENT_BLUE
    draw.rounded_rectangle([(split_x + 10, 70), (split_x + 145, 92)], radius=4, fill=tab1_bg)
    draw.text((split_x + 18, 74), "🖥 Visual Preview", fill=TEXT_WHITE)

    tab2_bg = ACCENT_BLUE if show_rust_tab else BG_PANEL
    draw.rounded_rectangle([(split_x + 155, 70), (split_x + 290, 92)], radius=4, fill=tab2_bg)
    draw.text((split_x + 165, 74), "🦀 Generated Rust", fill=TEXT_WHITE)

    draw.rounded_rectangle([(split_x + 300, 70), (split_x + 420, 92)], radius=4, fill=BG_PANEL)
    draw.text((split_x + 310, 74), "🌲 AST Inspector", fill=TEXT_DIM)

    # Tab Content
    if not show_rust_tab:
        # Visual Preview Display
        disp_x0 = split_x + 35
        disp_y0 = 125
        disp_w = 380
        disp_h = 285

        # Bezel frame
        draw.rounded_rectangle([(disp_x0 - 8, disp_y0 - 8), (disp_x0 + disp_w + 8, disp_y0 + disp_h + 8)], radius=10, fill=(35, 38, 46), outline=(65, 72, 85), width=2)
        # LCD Screen
        draw.rounded_rectangle([(disp_x0, disp_y0), (disp_x0 + disp_w, disp_y0 + disp_h)], radius=3, fill=BG_LCD)

        # Status bar in LCD
        draw.rectangle([(disp_x0, disp_y0), (disp_x0 + disp_w, disp_y0 + 26)], fill=(32, 36, 46))
        draw.text((disp_x0 + 8, disp_y0 + 6), "📶  🔋 98%", fill=TEXT_DIM)
        colon = ":" if int(t * 2) % 2 == 0 else " "
        draw.text((disp_x0 + disp_w - 55, disp_y0 + 6), f"14{colon}32", fill=TEXT_WHITE)

        # Oscilloscope Wave View
        scope_x0 = disp_x0 + 6
        scope_y0 = disp_y0 + 32
        scope_w = disp_w - 92
        scope_h = disp_h - 76
        draw.rounded_rectangle([(scope_x0, scope_y0), (scope_x0 + scope_w, scope_y0 + scope_h)], radius=3, fill=(12, 16, 22), outline=(35, 45, 60), width=1)

        # Grid lines in scope
        for i in range(1, 5):
            gx = scope_x0 + int(scope_w * i / 5)
            draw.line([(gx, scope_y0), (gx, scope_y0 + scope_h)], fill=(22, 30, 42), width=1)
        for i in range(1, 4):
            gy = scope_y0 + int(scope_h * i / 4)
            draw.line([(scope_x0, gy), (scope_x0 + scope_w, gy)], fill=(22, 30, 42), width=1)

        # Draw animated sine wave
        wave_pts = []
        center_y = scope_y0 + scope_h / 2
        amp = scope_h * 0.35
        for px in range(int(scope_w)):
            phase = (px * 0.08) - (t * 7.0)
            wy = center_y - (math.sin(phase) * amp * 0.8 + math.sin(phase * 2.0) * amp * 0.2)
            wave_pts.append((scope_x0 + px, wy))

        for i in range(len(wave_pts) - 1):
            draw.line([wave_pts[i], wave_pts[i + 1]], fill=ACCENT_CYAN, width=2)

        draw.text((scope_x0 + 6, scope_y0 + 6), "CH1: 1.00kHz (Live)", fill=ACCENT_CYAN)

        # Roller Drum Wheel (Right of scope)
        roller_x0 = scope_x0 + scope_w + 6
        roller_y0 = scope_y0
        roller_w = 74
        roller_h = scope_h
        draw.rounded_rectangle([(roller_x0, roller_y0), (roller_x0 + roller_w, roller_y0 + roller_h)], radius=4, fill=(24, 27, 34), outline=(55, 62, 75), width=1)

        row_h = roller_h / 3
        # Row 1: Prev (100mV)
        draw.text((roller_x0 + 16, roller_y0 + 15), "100mV", fill=TEXT_DIM)
        # Row 2: Selected (500mV)
        draw.rounded_rectangle([(roller_x0 + 3, roller_y0 + row_h + 2), (roller_x0 + roller_w - 3, roller_y0 + 2 * row_h - 2)], radius=3, fill=ACCENT_BLUE)
        draw.text((roller_x0 + 14, roller_y0 + row_h + 15), "500mV", fill=TEXT_WHITE)
        # Row 3: Next (1V)
        draw.text((roller_x0 + 24, roller_y0 + 2 * row_h + 15), "1V", fill=TEXT_DIM)

        # Bottom Buttons
        btn_y0 = disp_y0 + disp_h - 38
        draw.rounded_rectangle([(scope_x0, btn_y0), (scope_x0 + scope_w, btn_y0 + 32)], radius=4, fill=ACCENT_BLUE)
        draw.text((scope_x0 + scope_w // 2 - 35, btn_y0 + 9), "🔘 RUN/STOP", fill=TEXT_WHITE)

        draw.rounded_rectangle([(roller_x0, btn_y0), (roller_x0 + roller_w, btn_y0 + 32)], radius=4, fill=(50, 56, 68), outline=(80, 90, 105))
        draw.text((roller_x0 + 12, btn_y0 + 9), "SINGLE", fill=TEXT_WHITE)

        # Bottom metadata label
        draw.text((split_x + 35, H - 35), "Screen: ScopeScreen (320×240 px) • 60 FPS Continuous Motion Engine", fill=TEXT_DIM)

    else:
        # Generated Rust Code Tab
        draw.rectangle([(split_x + 10, 105), (W - 10, H - 20)], fill=(16, 18, 24), outline=BORDER_COLOR)
        y_rust = 118
        for line, color in RUST_LINES:
            draw.text((split_x + 24, y_rust), line, fill=color)
            y_rust += 17

    return img

def main():
    OUTPUT_GIF.parent.mkdir(parents=True, exist_ok=True)
    frames = []
    total_frames = 70
    print(f"Generating {total_frames} frames for {OUTPUT_GIF.name}...")

    for f in range(total_frames):
        img = create_frame(f, total_frames)
        frames.append(img)

    frames[0].save(
        OUTPUT_GIF,
        save_all=True,
        append_images=frames[1:],
        duration=50,  # 20 FPS
        loop=0,
        optimize=True,
    )
    print(f"-> Successfully created {OUTPUT_GIF} ({len(frames)} frames, {os.path.getsize(OUTPUT_GIF):,} bytes)")

if __name__ == "__main__":
    main()
